name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name : pull image from registry
      run : |
        docker pull sincha/nodeapp:latest

   

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with :
          image-ref: sincha/nodeapp:latest
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
         
          severity: 'CRITICAL,HIGH'

 

